### ISSUE TITLE
Tweaking size of font for Note List

### ISSUE THREAD

**Issue by michael-wenyon** [amandamcg/joplin-theme#7]
This theme works well for me on a 15" MacBook Pro.

On my Lenovo Thinkpad T450s, the Note list font is too small for me to read. How can I tweak this?

**Comment by michael-wenyon** [comment]
Just to clarify, I can for example change to the following in both css files, but then it makes the notebook list and the notes themselves in fonts that are too big. I want to only increase the font size in the note list:
`    --font-size: var(--base-size-24);`

**Comment by amandamcg** [comment]
Hey @michael-wenyon FYI I haven't been using this theme in awhile because I have been testing out the new, standard Joplin design (I think that new design was introduced around version 1.3.0). I just added a note to the readme to let people know.

To answer your question in particular, you can change the notebook list font size by editing this block around line 135. Currently it says: 
```
.side-bar .folders .list-item, .side-bar div, .side-bar span {
    color: var(--white) !important;
    font-weight: var(--font-weight-base) !important;
    font-size: var(--font-size) !important;
    margin-bottom: var(--base-size-1);
}
```

You should change the line that says `    font-size: var(--font-size) !important;` to be `    font-size: 30px !important;` or whatever font size you prefer. Make sure to always completely quit Joplin and restart after editing the CSS, otherwise it won't be applied.

**Comment by michael-wenyon** [comment]
Thanks. I switched to the standard too and could fix my problems using normal controls. Main problem is that I missed that 'global zoom %' had been removed from Options and replaced with a menu item to make text bigger or smaller (just posting this in case another earlier adopter is in the same situation).
